apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-storage-pv
  namespace: image-system

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteMany

  hostPath:
    path: /data/image-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage-pvc
  namespace: image-system

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 1Gi